-- liquibase formatted sql

-- changeset Imre:1703182311061-1
CREATE SEQUENCE IF NOT EXISTS refresh_token_seq START WITH 1 INCREMENT BY 50;

-- changeset Imre:1703182311061-2
CREATE TABLE jwt_token
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token               TEXT,
    time_period_minutes INTEGER                                 NOT NULL,
    issued_at_utc_time  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    expires_at_utc_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    scope               VARCHAR(255)                            NOT NULL,
    subject             VARCHAR(255)                            NOT NULL,
    user_name           VARCHAR(255)                            NOT NULL,
    ip                  VARCHAR(255),
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    um_user_id          BIGINT,
    CONSTRAINT pk_jwttoken PRIMARY KEY (id)
);

-- changeset Imre:1703182311061-3
CREATE TABLE password_reset_token
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token               VARCHAR(255)                            NOT NULL,
    user_name           VARCHAR(255)                            NOT NULL,
    user_email          VARCHAR(255)                            NOT NULL,
    time_period_minutes INTEGER                                 NOT NULL,
    issued_at_utc_time  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    expires_at_utc_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    um_user_id          BIGINT,
    CONSTRAINT pk_passwordresettoken PRIMARY KEY (id)
);

-- changeset Imre:1703182311061-4
CREATE TABLE refresh_token
(
    id                  BIGINT                      NOT NULL,
    um_user_id          BIGINT,
    user_name           VARCHAR(255)                NOT NULL,
    user_email          VARCHAR(255)                NOT NULL,
    token               VARCHAR(255)                NOT NULL,
    ip                  VARCHAR(255),
    time_period_minutes INTEGER                     NOT NULL,
    issued_at_utc_time  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    expires_at_utc_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_refreshtoken PRIMARY KEY (id)
);

-- changeset Imre:1703182311061-5
CREATE TABLE registration_token
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token               VARCHAR(255)                            NOT NULL,
    user_name           VARCHAR(255)                            NOT NULL,
    user_email          VARCHAR(255)                            NOT NULL,
    time_period_minutes INTEGER                                 NOT NULL,
    issued_at_utc_time  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    expires_at_utc_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    um_user_id          BIGINT,
    CONSTRAINT pk_registrationtoken PRIMARY KEY (id)
);

-- changeset Imre:1703182311061-6
CREATE TABLE roles_privileges
(
    privilege_id BIGINT NOT NULL,
    role_id      BIGINT NOT NULL
);

-- changeset Imre:1703182311061-7
CREATE TABLE um_user
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    status     VARCHAR(255),
    mfa_type   VARCHAR(255)                            NOT NULL,
    secret     VARCHAR(255),
    phone      VARCHAR(255),
    enabled    BOOLEAN                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_umuser PRIMARY KEY (id)
);

-- changeset Imre:1703182311061-8
CREATE TABLE um_user_privilege
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_umuserprivilege PRIMARY KEY (id)
);

-- changeset Imre:1703182311061-9
CREATE TABLE um_user_role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_umuserrole PRIMARY KEY (id)
);

-- changeset Imre:1703182311061-10
CREATE TABLE user_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

-- changeset Imre:1703182311061-11
ALTER TABLE um_user
    ADD CONSTRAINT uc_380765a3e1cea923a5b8937dc UNIQUE (email);

-- changeset Imre:1703182311061-12
ALTER TABLE registration_token
    ADD CONSTRAINT uc_8468b3693e7e515cef36f4c9e UNIQUE (token);

-- changeset Imre:1703182311061-13
ALTER TABLE password_reset_token
    ADD CONSTRAINT uc_c4f3c35083095cfc12f881d6a UNIQUE (token);

-- changeset Imre:1703182311061-14
ALTER TABLE refresh_token
    ADD CONSTRAINT uc_ddadc609b3b9f0e462885376b UNIQUE (token);

-- changeset Imre:1703182311061-15
CREATE INDEX "expiresAtUtcTime" ON jwt_token (expires_at_utc_time);

-- changeset Imre:1703182311061-16
CREATE INDEX "issuedAtUtcTime" ON jwt_token (issued_at_utc_time);

-- changeset Imre:1703182311061-17
CREATE INDEX name_idx ON um_user (name);

-- changeset Imre:1703182311061-18
CREATE INDEX scope ON jwt_token (scope);

-- changeset Imre:1703182311061-19
CREATE INDEX status_idx ON um_user (status);

-- changeset Imre:1703182311061-20
CREATE INDEX subject ON jwt_token (subject);

-- changeset Imre:1703182311061-21
CREATE INDEX "userName" ON jwt_token (user_name);

-- changeset Imre:1703182311061-22
ALTER TABLE jwt_token
    ADD CONSTRAINT FK_JWTTOKEN_ON_UM_USER FOREIGN KEY (um_user_id) REFERENCES um_user (id);

-- changeset Imre:1703182311061-23
ALTER TABLE password_reset_token
    ADD CONSTRAINT FK_PASSWORDRESETTOKEN_ON_UM_USER FOREIGN KEY (um_user_id) REFERENCES um_user (id);

-- changeset Imre:1703182311061-24
ALTER TABLE refresh_token
    ADD CONSTRAINT FK_REFRESHTOKEN_ON_UM_USER FOREIGN KEY (um_user_id) REFERENCES um_user (id);

-- changeset Imre:1703182311061-25
ALTER TABLE registration_token
    ADD CONSTRAINT FK_REGISTRATIONTOKEN_ON_UM_USER FOREIGN KEY (um_user_id) REFERENCES um_user (id);

-- changeset Imre:1703182311061-26
ALTER TABLE roles_privileges
    ADD CONSTRAINT fk_rolpri_on_um_user_privilege FOREIGN KEY (privilege_id) REFERENCES um_user_privilege (id);

-- changeset Imre:1703182311061-27
ALTER TABLE roles_privileges
    ADD CONSTRAINT fk_rolpri_on_um_user_role FOREIGN KEY (role_id) REFERENCES um_user_role (id);

-- changeset Imre:1703182311061-28
ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_um_user FOREIGN KEY (user_id) REFERENCES um_user (id);

-- changeset Imre:1703182311061-29
ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_um_user_role FOREIGN KEY (role_id) REFERENCES um_user_role (id);

