spring:
  thymeleaf:
    cache: false
  jpa:
    open-in-view: false
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    generate-unique-name: false
    name: um
  mail:
    host: smtp.gmail.com
    port: 587
    username: imre.tatai@graphtrek.co
    password: Almafa1...
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem