server:
  port : 8081
  shutdown: graceful

spring:
  config:
    import: classpath:env.properties
  thymeleaf:
    cache: false
  jpa:
    open-in-view: false
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    generate-unique-name: false
    name: um
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

application:
  name: UserManager

  adminUserName: ${ADMIN_USER_NAME}
  adminUserEmail: ${ADMIN_USER_EMAIL}
  adminUserPassword: ${ADMIN_USER_PASSWORD}
  adminUserRoles: ${ADMIN_USER_ROLES}