server:
  port : 8081
  shutdown: graceful

spring:
  config:
    import: classpath:env.properties
  thymeleaf:
    cache: false
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  datasource:
    #url: jdbc:h2:mem:um
    url: jdbc:h2:file:./data/h2/um;AUTO_SERVER=TRUE
    username: sa
    password:
    driverClassName: org.h2.Driver
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

application:
  name: UserManager

  adminUserName: ${ADMIN_USER_NAME}
  adminUserEmail: ${ADMIN_USER_EMAIL}
  adminUserPassword: ${ADMIN_USER_PASSWORD}
  adminUserRoles: ${ADMIN_USER_ROLES}